"""empty message

Revision ID: 325ef36b6f12
Revises: 22197ebaf70b
Create Date: 2020-11-01 13:47:38.792371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325ef36b6f12'
down_revision = '22197ebaf70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=False))
    op.alter_column('users', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
