"""empty message

Revision ID: 46179ce22f78
Revises: c0e9d3334c33
Create Date: 2020-12-07 00:25:19.802835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46179ce22f78'
down_revision = 'c0e9d3334c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
