"""empty message

Revision ID: 496491463a5b
Revises: 61360fe4497c
Create Date: 2020-12-06 18:46:55.819791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496491463a5b'
down_revision = '61360fe4497c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('levels', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'levels')
    # ### end Alembic commands ###
