"""empty message

Revision ID: 61360fe4497c
Revises: 132f794f7ed9
Create Date: 2020-12-06 18:04:31.540539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61360fe4497c'
down_revision = '132f794f7ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id_avatar',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'id_helmet',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id_helmet',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'id_avatar',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
